services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-netw
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    depends_on:
    - mongo
    - redis
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo-database
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-database
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongo-data:
